import FoodMomentSlider from "@/components/FoodMomentSlider";

const products = [
  { name: "Mix Grain Pap", type: "Pap", description: "A nourishing blend of carefully selected grains, processed smooth for satisfying family breakfasts." },
  { name: "Baby Special Pap", type: "Pap", description: "A smooth, nourishing pap option made with babies and growing children in mind." },
  { name: "Beans", type: "Everyday staple", description: "A dependable kitchen essential for moimoi, akara, beans cakes and hearty family meals." },
  { name: "Natural Honey", type: "Natural goodness", description: "A naturally sweet companion for pap, breakfast, drinks and everyday recipes." },
  { name: "Dates", type: "Natural goodness", description: "A naturally sweet food choice that fits snacks, recipes and nourishing everyday combinations." },
];

const benefits = [
  ["🌾", "Hygienically Processed", "Produced under clean and safe conditions."],
  ["🌽", "Quality Grains", "Made from carefully selected maize, millet and grains."],
  ["👶", "Nutritious & Healthy", "Thoughtfully made for everyday nourishment."],
  ["🚚", "Reliable Supply", "Fast response and dependable supply for homes and businesses."],
  ["💯", "Trusted Quality", "Consistent taste, freshness and satisfaction."],
  ["🇳🇬", "Proudly Nigerian", "Locally produced with care and excellence."],
];

export default function Home() {
  return (
    <main>
      <header className="absolute inset-x-0 top-0 z-20"><div className="container flex h-20 items-center justify-between"><a href="#" className="text-xl font-extrabold tracking-tight text-white">Depel&apos;s <span className="text-[var(--gold)]">Food Enterprise</span></a><nav className="hidden items-center gap-8 text-sm font-semibold text-white/90 md:flex"><a href="#products">Products</a><a href="#about">About</a><a href="#business">For Business</a><a href="#contact">Contact</a></nav><a href="#products" className="rounded-full bg-white px-5 py-2.5 text-sm font-bold text-[var(--green-dark)] shadow-lg">Order Now</a></div></header>

      <section className="relative min-h-[720px] overflow-hidden bg-[var(--green-dark)]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_45%,rgba(217,165,20,.25),transparent_34%),linear-gradient(110deg,rgba(8,47,24,.99),rgba(23,107,53,.82),rgba(8,47,24,.72))]" /><div className="absolute -right-28 top-28 h-[500px] w-[500px] rounded-full border border-white/10" /><div className="container relative flex min-h-[720px] items-center pt-24"><div className="max-w-2xl text-white"><p className="mb-5 inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.2em]">Quality food for everyday life</p><h1 className="font-[Montserrat] text-5xl font-extrabold leading-[.98] tracking-[-.04em] sm:text-6xl lg:text-[84px]">Good Food<br /><span className="text-[var(--gold)]">Gives More.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-white/80 sm:text-lg">From nourishing breakfasts to delicious everyday meals, Depel&apos;s brings carefully selected food products into the moments that matter most — at home, with family, and around the table.</p><div className="mt-9"><a href="#products" className="inline-flex rounded-full bg-[var(--gold)] px-7 py-4 text-sm font-extrabold text-white shadow-xl">Explore Our Products <span className="ml-3 text-lg">→</span></a></div></div></div></section>

      <FoodMomentSlider />

      <section id="about" className="bg-white py-24"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--gold)]">More than just food</p><h2 className="mt-4 font-[Montserrat] text-4xl font-extrabold leading-tight tracking-tight text-[var(--green-dark)] sm:text-5xl">Good choices should work together.</h2></div><p className="text-base leading-8 text-black/65 sm:text-lg">Depel&apos;s is growing into a trusted Nigerian food brand — bringing quality products together for the way people actually eat. Pap can meet honey at breakfast. Beans can become moimoi or akara. Dates and soya can add more possibilities to the everyday kitchen. One product can open the door to another.</p></div></section>

      <section id="products" className="bg-[var(--cream)] py-24"><div className="container"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--gold)]">Our growing range</p><h2 className="mt-3 font-[Montserrat] text-4xl font-extrabold tracking-tight text-[var(--green-dark)] sm:text-5xl">Products that belong in your kitchen.</h2><p className="mt-5 text-base leading-7 text-black/60">Choose what you need, then tell us what you want. More products are coming as we continue to grow.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{products.map((product, index) => <article key={product.name} className="group rounded-[26px] border border-black/5 bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="flex aspect-[4/3] items-center justify-center overflow-hidden rounded-[20px] bg-[var(--green-dark)]/8"><span className="text-xs font-semibold uppercase tracking-wider text-[var(--green-dark)]">Product image {index + 1}</span></div><p className="mt-5 text-[10px] font-bold uppercase tracking-[.18em] text-[var(--gold)]">{product.type}</p><h3 className="mt-1 text-lg font-extrabold text-[var(--green-dark)]">{product.name}</h3><p className="mt-2 text-sm leading-6 text-black/55">{product.description}</p><a href="#contact" className="mt-5 inline-flex rounded-full bg-[var(--green)] px-4 py-2.5 text-xs font-bold text-white">Choose &amp; Order</a></article>)}</div></div></section>

      <section className="bg-white py-24"><div className="container"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--gold)]">Why Depel&apos;s</p><h2 className="mt-3 font-[Montserrat] text-4xl font-extrabold tracking-tight text-[var(--green-dark)] sm:text-5xl">Made with care. Chosen with confidence.</h2></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(([icon,title,text]) => <div key={title} className="rounded-[22px] border border-black/5 bg-[var(--cream)] p-6"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-2xl shadow-sm">{icon}</div><h3 className="mt-5 font-bold text-[var(--green-dark)]">{title}</h3><p className="mt-2 text-sm leading-6 text-black/55">{text}</p></div>)}</div></div></section>

      <section id="business" className="bg-[var(--green-dark)] py-24 text-white"><div className="container flex flex-col justify-between gap-10 lg:flex-row lg:items-center"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--gold)]">For retailers &amp; businesses</p><h2 className="mt-4 font-[Montserrat] text-4xl font-extrabold leading-tight sm:text-5xl">Good food can grow your business too.</h2><p className="mt-5 text-base leading-8 text-white/70 sm:text-lg">We supply quality food products for retailers, caterers, food vendors, hospitality businesses and growing distributors.</p></div><a href="#contact" className="inline-flex w-fit rounded-full bg-[var(--gold)] px-7 py-4 text-sm font-extrabold text-white">Talk to Us About Supply →</a></div></section>

      <section className="bg-[var(--cream)] py-24"><div className="container text-center"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--gold)]">A little reminder</p><h2 className="mx-auto mt-4 max-w-3xl font-[Montserrat] text-4xl font-extrabold leading-tight text-[var(--green-dark)] sm:text-5xl">When the food is good, the moment becomes more.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-black/60">Breakfast becomes family time. Ingredients become a better meal. A good product becomes a better business.</p><a href="#products" className="mt-8 inline-flex rounded-full bg-[var(--green)] px-7 py-4 text-sm font-extrabold text-white">Find Your Products →</a></div></section>

      <footer id="contact" className="bg-[#082f18] py-14 text-white"><div className="container grid gap-10 md:grid-cols-3"><div><p className="text-xl font-extrabold">Depel&apos;s Food Enterprise</p><p className="mt-3 max-w-sm text-sm leading-6 text-white/55">Quality food products for everyday life, families and businesses.</p></div><div><p className="text-sm font-bold uppercase tracking-wider text-[var(--gold)]">Contact</p><p className="mt-3 text-sm text-white/70">+234 816 200 7086</p><p className="mt-2 text-sm text-white/70">executive@depelsfood.com</p><p className="mt-2 text-sm text-white/70">Osun State, Nigeria</p></div><div><p className="text-sm font-bold uppercase tracking-wider text-[var(--gold)]">Quick links</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm text-white/70"><a href="#">Home</a><a href="#about">About</a><a href="#products">Products</a><a href="#business">For Business</a></div></div></div><div className="container mt-12 border-t border-white/10 pt-6 text-xs text-white/40">© 2026 Depel&apos;s Food Enterprise. All Rights Reserved.</div></footer>
    </main>
  );
}
